Description: <short summary of the patch>
 TODO: Put a short summary on the line above and replace this paragraph
 with a longer explanation of this change. Complete the meta-information
 with other relevant fields (see below for details). To make it easier, the
 information below has been extracted from the changelog. Adjust it or drop
 it.
 .
 python-s3transfer (0.1.8-1) unstable; urgency=medium
 .
   * Initial release (Closes: #nnnn)  <nnnn is the bug number of your ITP>
Author: TANIGUCHI Takaki <takaki@debian.org>

---
The information above should follow the Patch Tagging Guidelines, please
checkout http://dep.debian.net/deps/dep3/ to learn about the format. Here
are templates for supplementary fields that you might want to add:

Origin: <vendor|upstream|other>, <url of original patch>
Bug: <url in upstream bugtracker>
Bug-Debian: https://bugs.debian.org/<bugnumber>
Bug-Ubuntu: https://launchpad.net/bugs/<bugnumber>
Forwarded: <no|not-needed|url proving that it has been forwarded>
Reviewed-By: <name and email of someone who approved the patch>
Last-Update: 2016-10-14

Index: python-s3transfer/s3transfer/__init__.py
===================================================================
--- python-s3transfer.orig/s3transfer/__init__.py	2019-02-27 17:09:55.254926657 +0900
+++ python-s3transfer/s3transfer/__init__.py	2019-02-27 17:09:55.250926726 +0900
@@ -134,7 +134,7 @@
 import concurrent.futures
 
 from botocore.compat import six
-from botocore.vendored.requests.packages.urllib3.exceptions import \
+from urllib3.exceptions import \
     ReadTimeoutError
 from botocore.exceptions import IncompleteReadError
 
Index: python-s3transfer/tests/unit/test_s3transfer.py
===================================================================
--- python-s3transfer.orig/tests/unit/test_s3transfer.py	2019-02-27 17:09:55.254926657 +0900
+++ python-s3transfer/tests/unit/test_s3transfer.py	2019-02-27 17:09:55.250926726 +0900
@@ -18,7 +18,7 @@
 from contextlib import closing
 
 import mock
-from botocore.vendored import six
+import six
 from concurrent import futures
 
 from s3transfer.exceptions import RetriesExceededError
